-- 授权新闻、公告、去重和标的关联数据域。

CREATE TABLE `news_source` (
  `id` bigint NOT NULL COMMENT '资讯来源 ID，由应用生成',
  `provider_id` bigint DEFAULT NULL COMMENT '提供该内容的外部 Provider ID',
  `source_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '内容来源唯一编码',
  `source_name` varchar(128) NOT NULL COMMENT '媒体、交易所、公司或监管机构名称',
  `source_type` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'MEDIA、EXCHANGE、COMPANY 或 REGULATOR',
  `homepage_url` varchar(1024) DEFAULT NULL,
  `authorization_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'AUTHORIZED' COMMENT 'AUTHORIZED、EXPIRED、SUSPENDED 或 UNKNOWN',
  `rights_valid_from` date DEFAULT NULL,
  `rights_valid_to` date DEFAULT NULL,
  `allow_ai_analysis` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '是否允许内容摘要进入 AI 上下文',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE、DEGRADED 或 DISABLED',
  `last_success_at` datetime(3) DEFAULT NULL,
  `last_failure_at` datetime(3) DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_news_source_code` (`source_code`),
  INDEX `idx_news_source_provider_status` (`provider_id`, `status`),
  INDEX `idx_news_source_rights` (`authorization_status`, `rights_valid_to`),
  CONSTRAINT `ck_news_source_type` CHECK (`source_type` IN ('MEDIA', 'EXCHANGE', 'COMPANY', 'REGULATOR')),
  CONSTRAINT `ck_news_source_auth` CHECK (`authorization_status` IN ('AUTHORIZED', 'EXPIRED', 'SUSPENDED', 'UNKNOWN')),
  CONSTRAINT `ck_news_source_ai_flag` CHECK (`allow_ai_analysis` IN (0, 1)),
  CONSTRAINT `ck_news_source_status` CHECK (`status` IN ('ACTIVE', 'DEGRADED', 'DISABLED')),
  CONSTRAINT `ck_news_source_rights_period` CHECK (`rights_valid_to` IS NULL OR `rights_valid_from` IS NULL OR `rights_valid_to` >= `rights_valid_from`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='授权资讯内容来源';

CREATE TABLE `stock_news` (
  `id` bigint NOT NULL COMMENT '资讯 ID，由应用生成',
  `source_id` bigint NOT NULL COMMENT '实际内容来源 ID，应用层维护关联',
  `provider_id` bigint DEFAULT NULL COMMENT '采集 Provider ID，应用层维护关联',
  `source_content_id` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '来源侧稿件唯一标识',
  `news_type` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'NEWS、ANNOUNCEMENT、RESEARCH 或 OTHER',
  `title` varchar(500) NOT NULL,
  `authorized_summary` text DEFAULT NULL COMMENT '授权范围内可展示和分析的摘要',
  `author_name` varchar(128) DEFAULT NULL,
  `original_url` varchar(1024) NOT NULL,
  `language_code` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'zh-CN',
  `published_at` datetime(3) NOT NULL COMMENT '来源发布时间',
  `collected_at` datetime(3) NOT NULL COMMENT '平台采集时间',
  `content_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '清洗后内容 SHA-256',
  `canonical_news_id` bigint DEFAULT NULL COMMENT '跨来源重复稿件指向的主记录 ID',
  `dedup_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ORIGINAL' COMMENT 'ORIGINAL 或 DUPLICATE',
  `content_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PUBLISHED' COMMENT 'PUBLISHED、WITHDRAWN 或 DELETED',
  `original_access_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'UNKNOWN' COMMENT 'AVAILABLE、UNAVAILABLE 或 UNKNOWN',
  `last_url_checked_at` datetime(3) DEFAULT NULL,
  `rights_expire_at` datetime(3) DEFAULT NULL COMMENT '单条内容授权失效时间',
  `extension_data` json DEFAULT NULL COMMENT '已清洗的供应商非核心扩展字段',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_stock_news_source_content` (`source_id`, `source_content_id`),
  INDEX `idx_stock_news_publish` (`content_status`, `published_at` DESC, `id`),
  INDEX `idx_stock_news_type_publish` (`news_type`, `published_at` DESC, `id`),
  INDEX `idx_stock_news_fingerprint` (`content_fingerprint`, `published_at`),
  INDEX `idx_stock_news_canonical` (`canonical_news_id`, `dedup_status`),
  INDEX `idx_stock_news_rights` (`rights_expire_at`, `content_status`),
  CONSTRAINT `ck_stock_news_type` CHECK (`news_type` IN ('NEWS', 'ANNOUNCEMENT', 'RESEARCH', 'OTHER')),
  CONSTRAINT `ck_stock_news_dedup` CHECK (`dedup_status` IN ('ORIGINAL', 'DUPLICATE')),
  CONSTRAINT `ck_stock_news_content_status` CHECK (`content_status` IN ('PUBLISHED', 'WITHDRAWN', 'DELETED')),
  CONSTRAINT `ck_stock_news_access_status` CHECK (`original_access_status` IN ('AVAILABLE', 'UNAVAILABLE', 'UNKNOWN')),
  CONSTRAINT `ck_stock_news_canonical` CHECK (
    (`dedup_status` = 'ORIGINAL' AND `canonical_news_id` IS NULL)
    OR (`dedup_status` = 'DUPLICATE' AND `canonical_news_id` IS NOT NULL AND `canonical_news_id` <> `id`)
  )
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='股票新闻与公告';

CREATE TABLE `stock_news_relation` (
  `id` bigint NOT NULL COMMENT '资讯关联 ID，由应用生成',
  `news_id` bigint NOT NULL COMMENT '资讯 ID，应用层维护关联',
  `target_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SECURITY、SECTOR 或 MARKET',
  `target_id` bigint NOT NULL COMMENT '目标对象 ID',
  `relation_method` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'EXPLICIT、RULE、MODEL 或 MANUAL',
  `confidence_score` decimal(6,5) DEFAULT NULL COMMENT '0 到 1，显式关联可为空',
  `relation_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CONFIRMED' COMMENT 'CONFIRMED、CANDIDATE 或 REJECTED',
  `reason_summary` varchar(500) DEFAULT NULL COMMENT '关联依据摘要',
  `reviewed_by` bigint DEFAULT NULL COMMENT '人工复核用户 ID',
  `reviewed_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_news_relation_target` (`news_id`, `target_type`, `target_id`),
  INDEX `idx_news_relation_target_status` (`target_type`, `target_id`, `relation_status`, `news_id`),
  INDEX `idx_news_relation_news_status` (`news_id`, `relation_status`),
  CONSTRAINT `ck_news_relation_target` CHECK (`target_type` IN ('SECURITY', 'SECTOR', 'MARKET')),
  CONSTRAINT `ck_news_relation_method` CHECK (`relation_method` IN ('EXPLICIT', 'RULE', 'MODEL', 'MANUAL')),
  CONSTRAINT `ck_news_relation_status` CHECK (`relation_status` IN ('CONFIRMED', 'CANDIDATE', 'REJECTED')),
  CONSTRAINT `ck_news_relation_confidence` CHECK (`confidence_score` IS NULL OR (`confidence_score` >= 0 AND `confidence_score` <= 1))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='资讯与证券、板块或市场关联';
