-- AI 研究会话、异步任务、上下文、报告、证据、反馈和用量数据域。

CREATE TABLE `ai_session` (
  `id` bigint NOT NULL COMMENT 'AI 会话 ID，由应用生成',
  `user_id` bigint NOT NULL COMMENT '所属用户 ID，应用层维护关联',
  `scene` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'MARKET、SECTOR、STOCK、STOCK_RISK 或 COMPARE',
  `title` varchar(120) NOT NULL COMMENT '会话标题',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE、READ_ONLY 或 DELETED',
  `is_favorite` tinyint unsigned NOT NULL DEFAULT 0,
  `last_task_id` bigint DEFAULT NULL COMMENT '最近任务 ID，应用层维护关联',
  `last_activity_at` datetime(3) NOT NULL COMMENT '最后消息或任务活动时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '用户删除时间',
  `purge_after` datetime(3) DEFAULT NULL COMMENT '物理清理时间，通常为删除后 30 天',
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_ai_session_user_activity` (`user_id`, `status`, `last_activity_at` DESC, `id`),
  INDEX `idx_ai_session_user_scene` (`user_id`, `scene`, `last_activity_at` DESC),
  INDEX `idx_ai_session_purge` (`status`, `purge_after`),
  CONSTRAINT `ck_ai_session_scene` CHECK (`scene` IN ('MARKET', 'SECTOR', 'STOCK', 'STOCK_RISK', 'COMPARE')),
  CONSTRAINT `ck_ai_session_status` CHECK (`status` IN ('ACTIVE', 'READ_ONLY', 'DELETED')),
  CONSTRAINT `ck_ai_session_favorite` CHECK (`is_favorite` IN (0, 1)),
  CONSTRAINT `ck_ai_session_delete_state` CHECK (
    (`status` <> 'DELETED' AND `deleted_at` IS NULL AND `purge_after` IS NULL)
    OR (`status` = 'DELETED' AND `deleted_at` IS NOT NULL AND `purge_after` IS NOT NULL AND `purge_after` >= `deleted_at`)
  )
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='用户 AI 研究会话';

CREATE TABLE `ai_task` (
  `id` bigint NOT NULL COMMENT 'AI 任务 ID，由应用生成',
  `request_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '客户端幂等请求 UUID',
  `session_id` bigint NOT NULL COMMENT '会话 ID，应用层维护关联',
  `user_id` bigint NOT NULL COMMENT '用户 ID，冗余用于鉴权和配额查询',
  `retry_of_task_id` bigint DEFAULT NULL COMMENT '用户重试时关联原任务 ID',
  `scene` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `question` varchar(1000) DEFAULT NULL COMMENT '用户问题，应用限制最多 500 字符',
  `analysis_start_at` datetime(3) DEFAULT NULL COMMENT '用户选择的分析区间开始',
  `analysis_end_at` datetime(3) DEFAULT NULL COMMENT '用户选择的分析区间结束',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CREATED' COMMENT '任务状态机',
  `priority_no` tinyint unsigned NOT NULL DEFAULT 5 COMMENT '0 最高，9 最低',
  `attempt_no` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '已开始的执行次数',
  `max_attempts` tinyint unsigned NOT NULL DEFAULT 2 COMMENT '自动重试一次时总尝试上限为 2',
  `cancel_requested` tinyint unsigned NOT NULL DEFAULT 0,
  `provider_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `model_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `queued_at` datetime(3) DEFAULT NULL,
  `started_at` datetime(3) DEFAULT NULL,
  `first_chunk_at` datetime(3) DEFAULT NULL COMMENT '首段内容产生时间',
  `validating_at` datetime(3) DEFAULT NULL,
  `heartbeat_at` datetime(3) DEFAULT NULL,
  `deadline_at` datetime(3) DEFAULT NULL COMMENT '超过该时间进入超时处理',
  `completed_at` datetime(3) DEFAULT NULL,
  `error_category` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'TIMEOUT、RATE_LIMIT、DATA、SAFETY、PROVIDER 或 SYSTEM',
  `error_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `error_message` varchar(1000) DEFAULT NULL COMMENT '可审计的脱敏错误摘要',
  `trace_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '任务状态乐观锁版本',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ai_task_request_id` (`request_id`),
  INDEX `idx_ai_task_user_created` (`user_id`, `created_at` DESC, `id`),
  INDEX `idx_ai_task_user_status` (`user_id`, `status`, `created_at` DESC),
  INDEX `idx_ai_task_session_created` (`session_id`, `created_at`, `id`),
  INDEX `idx_ai_task_recovery` (`status`, `heartbeat_at`, `deadline_at`),
  INDEX `idx_ai_task_retry` (`retry_of_task_id`),
  INDEX `idx_ai_task_trace` (`trace_id`),
  CONSTRAINT `ck_ai_task_scene` CHECK (`scene` IN ('MARKET', 'SECTOR', 'STOCK', 'STOCK_RISK', 'COMPARE')),
  CONSTRAINT `ck_ai_task_status` CHECK (`status` IN ('CREATED', 'PREPARING', 'QUEUED', 'RUNNING', 'VALIDATING', 'COMPLETED', 'CANCELED', 'FAILED', 'TIMED_OUT')),
  CONSTRAINT `ck_ai_task_priority` CHECK (`priority_no` <= 9),
  CONSTRAINT `ck_ai_task_attempts` CHECK (`max_attempts` BETWEEN 1 AND 5 AND `attempt_no` <= `max_attempts`),
  CONSTRAINT `ck_ai_task_cancel` CHECK (`cancel_requested` IN (0, 1)),
  CONSTRAINT `ck_ai_task_question_length` CHECK (`question` IS NULL OR CHAR_LENGTH(`question`) <= 500),
  CONSTRAINT `ck_ai_task_analysis_period` CHECK (`analysis_end_at` IS NULL OR `analysis_start_at` IS NULL OR `analysis_end_at` >= `analysis_start_at`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='异步 AI 分析任务';

CREATE TABLE `ai_task_target` (
  `id` bigint NOT NULL COMMENT '任务目标 ID，由应用生成',
  `task_id` bigint NOT NULL COMMENT 'AI 任务 ID，应用层维护关联',
  `target_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'MARKET、SECTOR 或 SECURITY',
  `target_id` bigint NOT NULL COMMENT '目标业务 ID',
  `target_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '任务时的目标代码快照',
  `target_name` varchar(128) NOT NULL COMMENT '任务时的目标名称快照',
  `target_role` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PRIMARY' COMMENT 'PRIMARY、COMPARISON 或 CONTEXT',
  `sort_no` tinyint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ai_task_target` (`task_id`, `target_type`, `target_id`, `target_role`),
  INDEX `idx_ai_target_history` (`target_type`, `target_id`, `task_id`),
  INDEX `idx_ai_target_task_sort` (`task_id`, `sort_no`),
  CONSTRAINT `ck_ai_target_type` CHECK (`target_type` IN ('MARKET', 'SECTOR', 'SECURITY')),
  CONSTRAINT `ck_ai_target_role` CHECK (`target_role` IN ('PRIMARY', 'COMPARISON', 'CONTEXT'))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='AI 任务分析目标';

CREATE TABLE `ai_context_snapshot` (
  `id` bigint NOT NULL COMMENT '上下文快照 ID，由应用生成',
  `task_id` bigint NOT NULL COMMENT 'AI 任务 ID，应用层维护关联',
  `snapshot_no` int unsigned NOT NULL COMMENT '任务内稳定顺序，从 1 开始',
  `context_type` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'QUOTE、KLINE、SECTOR、BUSINESS、NEWS、CALENDAR 或 RULE',
  `source_object_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '内部来源对象类型',
  `source_object_id` bigint DEFAULT NULL COMMENT '内部来源对象 ID',
  `source_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '无内部 ID 时使用的稳定来源键',
  `data_time` datetime(3) DEFAULT NULL COMMENT '该条事实对应的数据时间',
  `data_cutoff_at` datetime(3) NOT NULL COMMENT '任务固化该类数据的截止时间',
  `content_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `context_data` json NOT NULL COMMENT '去敏、清洗后的结构化上下文',
  `is_evidence_candidate` tinyint unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ai_context_task_no` (`task_id`, `snapshot_no`),
  INDEX `idx_ai_context_task_type` (`task_id`, `context_type`, `data_time`),
  INDEX `idx_ai_context_source` (`source_object_type`, `source_object_id`, `data_time`),
  CONSTRAINT `ck_ai_context_type` CHECK (`context_type` IN ('QUOTE', 'KLINE', 'SECTOR', 'BUSINESS', 'NEWS', 'CALENDAR', 'RULE')),
  CONSTRAINT `ck_ai_context_evidence` CHECK (`is_evidence_candidate` IN (0, 1)),
  CONSTRAINT `ck_ai_context_snapshot_no` CHECK (`snapshot_no` >= 1)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='AI 任务冻结上下文';

CREATE TABLE `ai_message` (
  `id` bigint NOT NULL COMMENT '消息 ID，由应用生成',
  `session_id` bigint NOT NULL COMMENT '会话 ID，应用层维护关联',
  `task_id` bigint DEFAULT NULL COMMENT '产生或消费该消息的任务 ID',
  `role_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'USER、ASSISTANT 或 SYSTEM',
  `sequence_no` int unsigned NOT NULL COMMENT '会话内稳定顺序，从 1 开始',
  `content_format` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MARKDOWN' COMMENT 'PLAIN、MARKDOWN 或 JSON',
  `content` longtext NOT NULL COMMENT '消息正文',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'COMPLETED' COMMENT 'DRAFT、STREAMING、COMPLETED、FAILED 或 DELETED',
  `data_cutoff_at` datetime(3) DEFAULT NULL COMMENT '回答所使用数据的综合截止时间',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ai_message_session_sequence` (`session_id`, `sequence_no`),
  INDEX `idx_ai_message_task` (`task_id`, `role_type`),
  INDEX `idx_ai_message_session_status` (`session_id`, `status`, `sequence_no`),
  CONSTRAINT `ck_ai_message_role` CHECK (`role_type` IN ('USER', 'ASSISTANT', 'SYSTEM')),
  CONSTRAINT `ck_ai_message_format` CHECK (`content_format` IN ('PLAIN', 'MARKDOWN', 'JSON')),
  CONSTRAINT `ck_ai_message_status` CHECK (`status` IN ('DRAFT', 'STREAMING', 'COMPLETED', 'FAILED', 'DELETED')),
  CONSTRAINT `ck_ai_message_sequence` CHECK (`sequence_no` >= 1)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='AI 会话消息';

CREATE TABLE `ai_report` (
  `id` bigint NOT NULL COMMENT '分析报告 ID，由应用生成',
  `task_id` bigint NOT NULL COMMENT 'AI 任务 ID，一项任务最多一个最终报告',
  `session_id` bigint NOT NULL COMMENT '会话 ID，冗余用于历史查询',
  `assistant_message_id` bigint DEFAULT NULL COMMENT '对应的助手消息 ID',
  `core_conclusion` longtext NOT NULL COMMENT '核心结论',
  `quote_evidence` longtext NOT NULL COMMENT '行情与量价依据',
  `comparison_analysis` longtext DEFAULT NULL COMMENT '市场、板块或多标的对比',
  `event_clues` longtext DEFAULT NULL COMMENT '资讯与事件线索',
  `risk_and_uncertainty` longtext NOT NULL COMMENT '风险、反例和不确定性',
  `disclaimer` varchar(1000) NOT NULL COMMENT '非投资建议声明',
  `rendered_markdown` longtext NOT NULL COMMENT '固定章节的完整渲染内容',
  `is_limited` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '1表示证据不足的受限分析',
  `limited_reason` varchar(500) DEFAULT NULL,
  `quality_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'VALID' COMMENT 'VALID 或 LIMITED；校验拒绝结果不生成报告',
  `content_schema_version` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `prompt_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `provider_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `model_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `market_data_cutoff_at` datetime(3) NOT NULL,
  `news_data_cutoff_at` datetime(3) DEFAULT NULL,
  `content_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `generated_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ai_report_task` (`task_id`),
  INDEX `idx_ai_report_session_generated` (`session_id`, `generated_at` DESC, `id`),
  INDEX `idx_ai_report_quality_generated` (`quality_status`, `generated_at` DESC),
  CONSTRAINT `ck_ai_report_limited` CHECK (`is_limited` IN (0, 1)),
  CONSTRAINT `ck_ai_report_quality` CHECK (`quality_status` IN ('VALID', 'LIMITED')),
  CONSTRAINT `ck_ai_report_limit_state` CHECK (
    (`is_limited` = 0 AND `quality_status` = 'VALID' AND `limited_reason` IS NULL)
    OR (`is_limited` = 1 AND `quality_status` = 'LIMITED' AND `limited_reason` IS NOT NULL)
  )
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='结构化 AI 分析报告';

CREATE TABLE `ai_evidence` (
  `id` bigint NOT NULL COMMENT '证据 ID，由应用生成',
  `report_id` bigint NOT NULL COMMENT '报告 ID，应用层维护关联',
  `evidence_no` int unsigned NOT NULL COMMENT '报告内证据编号，从 1 开始',
  `context_snapshot_id` bigint DEFAULT NULL COMMENT '引用的任务上下文快照 ID',
  `evidence_type` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'QUOTE、KLINE、NEWS、ANNOUNCEMENT、BUSINESS、SECTOR 或 RULE',
  `source_object_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_object_id` bigint DEFAULT NULL,
  `source_title` varchar(500) NOT NULL,
  `source_url` varchar(1024) DEFAULT NULL,
  `evidence_summary` varchar(2000) NOT NULL COMMENT '授权范围内的事实摘要，不保存伪造引用',
  `source_published_at` datetime(3) DEFAULT NULL,
  `data_time` datetime(3) DEFAULT NULL,
  `access_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'AVAILABLE' COMMENT 'AVAILABLE、UNAVAILABLE 或 RESTRICTED',
  `content_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ai_evidence_report_no` (`report_id`, `evidence_no`),
  INDEX `idx_ai_evidence_context` (`context_snapshot_id`),
  INDEX `idx_ai_evidence_source` (`source_object_type`, `source_object_id`, `data_time`),
  CONSTRAINT `ck_ai_evidence_no` CHECK (`evidence_no` >= 1),
  CONSTRAINT `ck_ai_evidence_type` CHECK (`evidence_type` IN ('QUOTE', 'KLINE', 'NEWS', 'ANNOUNCEMENT', 'BUSINESS', 'SECTOR', 'RULE')),
  CONSTRAINT `ck_ai_evidence_access` CHECK (`access_status` IN ('AVAILABLE', 'UNAVAILABLE', 'RESTRICTED'))
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='AI 报告来源证据';

CREATE TABLE `ai_feedback` (
  `id` bigint NOT NULL COMMENT '反馈 ID，由应用生成',
  `report_id` bigint NOT NULL COMMENT '报告 ID，应用层维护关联',
  `user_id` bigint NOT NULL COMMENT '反馈用户 ID',
  `feedback_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'HELPFUL 或 NOT_HELPFUL',
  `reason_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'FACT_ERROR、CITATION_ERROR、OVER_INFERENCE、OFF_TOPIC 或 OUTDATED',
  `detail` varchar(600) DEFAULT NULL COMMENT '应用限制最多 300 字符',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ai_feedback_report_user` (`report_id`, `user_id`),
  INDEX `idx_ai_feedback_user_time` (`user_id`, `updated_at` DESC),
  INDEX `idx_ai_feedback_type_reason` (`feedback_type`, `reason_code`, `updated_at`),
  CONSTRAINT `ck_ai_feedback_type` CHECK (`feedback_type` IN ('HELPFUL', 'NOT_HELPFUL')),
  CONSTRAINT `ck_ai_feedback_reason` CHECK (`reason_code` IS NULL OR `reason_code` IN ('FACT_ERROR', 'CITATION_ERROR', 'OVER_INFERENCE', 'OFF_TOPIC', 'OUTDATED')),
  CONSTRAINT `ck_ai_feedback_detail` CHECK (`detail` IS NULL OR CHAR_LENGTH(`detail`) <= 300)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='用户对 AI 报告的反馈';

CREATE TABLE `ai_usage` (
  `id` bigint NOT NULL COMMENT '调用用量 ID，由应用生成',
  `task_id` bigint NOT NULL COMMENT 'AI 任务 ID，每次实际 Provider 调用一条记录',
  `attempt_no` tinyint unsigned NOT NULL COMMENT '对应任务执行次数',
  `user_id` bigint NOT NULL COMMENT '用户 ID，冗余用于配额与成本汇总',
  `provider_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `model_code` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `provider_request_id` varchar(191) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `prompt_tokens` int unsigned NOT NULL DEFAULT 0,
  `completion_tokens` int unsigned NOT NULL DEFAULT 0,
  `cached_tokens` int unsigned NOT NULL DEFAULT 0,
  `total_tokens` int unsigned NOT NULL DEFAULT 0,
  `estimated_cost` decimal(18,8) NOT NULL DEFAULT 0 COMMENT '内部成本估算，不直接面向用户',
  `currency_code` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CNY',
  `first_chunk_latency_ms` int unsigned DEFAULT NULL,
  `total_latency_ms` int unsigned DEFAULT NULL,
  `result_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SUCCESS、FAILURE、CANCELED 或 TIMED_OUT',
  `error_category` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `call_started_at` datetime(3) NOT NULL,
  `call_completed_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ai_usage_task_attempt` (`task_id`, `attempt_no`),
  INDEX `idx_ai_usage_user_time` (`user_id`, `call_started_at` DESC),
  INDEX `idx_ai_usage_provider_time` (`provider_code`, `model_code`, `call_started_at` DESC),
  INDEX `idx_ai_usage_status_time` (`result_status`, `call_started_at` DESC),
  CONSTRAINT `ck_ai_usage_attempt` CHECK (`attempt_no` >= 1),
  CONSTRAINT `ck_ai_usage_status` CHECK (`result_status` IN ('SUCCESS', 'FAILURE', 'CANCELED', 'TIMED_OUT')),
  CONSTRAINT `ck_ai_usage_tokens` CHECK (`total_tokens` >= `prompt_tokens` + `completion_tokens`),
  CONSTRAINT `ck_ai_usage_period` CHECK (`call_completed_at` IS NULL OR `call_completed_at` >= `call_started_at`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='大模型调用用量与成本';
