-- 后台任务执行、数据质量隔离和事务 Outbox。

CREATE TABLE `job_execution_summary` (
  `id` bigint NOT NULL COMMENT '执行记录 ID，由应用生成',
  `job_name` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '稳定业务任务名称',
  `handler_name` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'XXL-JOB Handler 名称',
  `batch_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '同次任务各分片共享批次 ID',
  `provider_id` bigint DEFAULT NULL COMMENT '关联外部 Provider ID',
  `trigger_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SCHEDULED、MANUAL、RETRY 或 RECOVERY',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'RUNNING' COMMENT 'RUNNING、SUCCESS、PARTIAL、FAILED 或 CANCELED',
  `shard_index` int unsigned NOT NULL DEFAULT 0,
  `shard_total` int unsigned NOT NULL DEFAULT 1,
  `attempt_no` tinyint unsigned NOT NULL DEFAULT 1,
  `scheduled_at` datetime(3) DEFAULT NULL,
  `started_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `source_data_start_at` datetime(3) DEFAULT NULL,
  `source_data_end_at` datetime(3) DEFAULT NULL,
  `input_count` bigint unsigned NOT NULL DEFAULT 0,
  `success_count` bigint unsigned NOT NULL DEFAULT 0,
  `ignored_count` bigint unsigned NOT NULL DEFAULT 0,
  `failure_count` bigint unsigned NOT NULL DEFAULT 0,
  `output_count` bigint unsigned NOT NULL DEFAULT 0,
  `error_category` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `error_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `error_summary` varchar(1000) DEFAULT NULL COMMENT '脱敏错误摘要',
  `trace_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_job_execution_batch_shard_attempt` (`job_name`, `batch_id`, `shard_index`, `attempt_no`),
  INDEX `idx_job_execution_name_time` (`job_name`, `started_at` DESC, `id`),
  INDEX `idx_job_execution_status_time` (`status`, `started_at`),
  INDEX `idx_job_execution_provider_time` (`provider_id`, `started_at` DESC),
  INDEX `idx_job_execution_trace` (`trace_id`),
  CONSTRAINT `ck_job_execution_trigger` CHECK (`trigger_type` IN ('SCHEDULED', 'MANUAL', 'RETRY', 'RECOVERY')),
  CONSTRAINT `ck_job_execution_status` CHECK (`status` IN ('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'CANCELED')),
  CONSTRAINT `ck_job_execution_shard` CHECK (`shard_total` >= 1 AND `shard_index` < `shard_total`),
  CONSTRAINT `ck_job_execution_attempt` CHECK (`attempt_no` >= 1),
  CONSTRAINT `ck_job_execution_period` CHECK (`completed_at` IS NULL OR `completed_at` >= `started_at`),
  CONSTRAINT `ck_job_execution_source_period` CHECK (`source_data_end_at` IS NULL OR `source_data_start_at` IS NULL OR `source_data_end_at` >= `source_data_start_at`),
  CONSTRAINT `ck_job_execution_counts` CHECK (`success_count` + `ignored_count` + `failure_count` <= `input_count`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='业务定时任务执行摘要';

CREATE TABLE `data_quality_issue` (
  `id` bigint NOT NULL COMMENT '质量问题 ID，由应用生成',
  `batch_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '采集或聚合批次 ID',
  `data_domain` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SECURITY、QUOTE、KLINE、SECTOR、INDEX 或 NEWS',
  `object_type` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `object_key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '可定位但不含敏感信息的业务键',
  `issue_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `severity` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'INFO、WARNING、ERROR 或 CRITICAL',
  `reason_summary` varchar(1000) NOT NULL,
  `raw_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '原始记录摘要哈希，不保存完整响应',
  `sanitized_sample` json DEFAULT NULL COMMENT '用于排障的去敏最小样本',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN、IGNORED 或 RESOLVED',
  `resolved_by` bigint DEFAULT NULL COMMENT '处理用户 ID',
  `resolved_at` datetime(3) DEFAULT NULL,
  `resolution_summary` varchar(1000) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_data_quality_issue_object` (`batch_id`, `data_domain`, `object_type`, `object_key`, `issue_code`),
  INDEX `idx_data_quality_status_severity` (`status`, `severity`, `created_at`),
  INDEX `idx_data_quality_domain_time` (`data_domain`, `created_at` DESC),
  CONSTRAINT `ck_data_quality_domain` CHECK (`data_domain` IN ('SECURITY', 'QUOTE', 'KLINE', 'SECTOR', 'INDEX', 'NEWS')),
  CONSTRAINT `ck_data_quality_severity` CHECK (`severity` IN ('INFO', 'WARNING', 'ERROR', 'CRITICAL')),
  CONSTRAINT `ck_data_quality_status` CHECK (`status` IN ('OPEN', 'IGNORED', 'RESOLVED')),
  CONSTRAINT `ck_data_quality_resolution` CHECK (
    (`status` = 'OPEN' AND `resolved_at` IS NULL)
    OR (`status` IN ('IGNORED', 'RESOLVED') AND `resolved_at` IS NOT NULL)
  )
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='数据质量隔离与处理记录';

CREATE TABLE `event_outbox` (
  `id` bigint NOT NULL COMMENT 'Outbox 记录 ID，由应用生成',
  `event_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '事件幂等 UUID',
  `aggregate_type` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '业务聚合类型',
  `aggregate_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '业务聚合 ID',
  `event_type` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `destination_type` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'REDIS_STREAM、REDIS_PUBSUB 或 CACHE_INVALIDATION',
  `partition_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `event_payload` json NOT NULL COMMENT '去敏后的事件载荷',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'NEW' COMMENT 'NEW、PUBLISHING、PUBLISHED、FAILED 或 DEAD',
  `attempt_count` int unsigned NOT NULL DEFAULT 0,
  `max_attempts` int unsigned NOT NULL DEFAULT 10,
  `available_at` datetime(3) NOT NULL COMMENT '允许下次发布的时间',
  `locked_by` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `locked_at` datetime(3) DEFAULT NULL,
  `published_at` datetime(3) DEFAULT NULL,
  `last_error_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `last_error_summary` varchar(1000) DEFAULT NULL COMMENT '脱敏错误摘要',
  `trace_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_event_outbox_event_id` (`event_id`),
  INDEX `idx_event_outbox_dispatch` (`status`, `available_at`, `id`),
  INDEX `idx_event_outbox_lock` (`status`, `locked_at`),
  INDEX `idx_event_outbox_aggregate` (`aggregate_type`, `aggregate_id`, `created_at`),
  INDEX `idx_event_outbox_trace` (`trace_id`),
  CONSTRAINT `ck_event_outbox_destination` CHECK (`destination_type` IN ('REDIS_STREAM', 'REDIS_PUBSUB', 'CACHE_INVALIDATION')),
  CONSTRAINT `ck_event_outbox_status` CHECK (`status` IN ('NEW', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'DEAD')),
  CONSTRAINT `ck_event_outbox_attempts` CHECK (`max_attempts` >= 1 AND `attempt_count` <= `max_attempts`),
  CONSTRAINT `ck_event_outbox_publish_state` CHECK (
    (`status` = 'PUBLISHED' AND `published_at` IS NOT NULL)
    OR (`status` <> 'PUBLISHED')
  )
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='事务事件 Outbox';
